name: Check
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.47
      - name: set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: test
        run: go test -v ./...